### PR TITLE
chore: add license to package.json

### PR DESCRIPTION
**Pull request by edodusi**

### CODE REVIEW

**Comment by alvarosabu** [comment]
@edodusi I think you might need to use fix as commit otherwise it will not trigger a release

**Comment by johannes-lindgren** [comment]
@alvarosabu, @edodusi, the package will be published to NPM when you create a GitHub release: https://github.com/storyblok/app-extension-auth/blob/main/.github/workflows/npm-publish-library.yml

**Review by johannes-lindgren — APPROVED** [review]

**Comment by johannes-lindgren** [comment]
Can I get write access again? I mean, I am the original author 😉 

image

**Comment by edodusi** [comment]
@johannes-lindgren I will check with the admin team and get back to you!

**Review by christianzoppi — APPROVED** [review]

**Pull request merged**
