### PR TITLE
chore: release @storyblok/app-extension-auth@1.0.0-alpha.0

### PR DESCRIPTION
**Pull request by johannes-lindgren**
Issue: EXT-1589

Bumping alpha version. Since the previous version did not have `.0` suffix, this version starts with `.1`.

The Readme also got a few minor updates.

The license field is removed. That was decided in the company after this library had been created.

### CODE REVIEW

**Comment by eunjae-lee** [comment]
Since we've introduced a breaking change, we should bump a major version (so, `1.0.0-alpha.0`). What do you think?

**Comment by johannes-lindgren** [comment]
@eunjae-lee  Okay, let's do that 👍

**Comment by johannes-lindgren** [comment]
@eunjae-lee I also renamed the title, so that it matches the pattern we use in @storyblok/field-plugin

> chore: release @storyblok/app-extension-auth@1.0.0-alpha.0

**Review by eunjae-lee — APPROVED** [review]
Let's go!

**Pull request merged**
