### PR TITLE
fix: use region-helper instead of hardcoded region functions

### PR DESCRIPTION
**Pull request by BibiSebi**
Issue:

## What?
This PR includes using the new region-helper instead of hardcoded logic.

## Why?

[EXT-2122](https://storyblok.atlassian.net/browse/EXT-2122)

## How to test? (optional)
1. run `yarn build`
2. run `yarn pack`
3. copy-paste the packed file (package.tgz) to your space/tool plugin
4. adapt package.json to use the local dependency from the packed file (e.g.: `@storyblok/app-extension-auth: "file:./../your-desintation/package.tgz`") 
5. test the space/tool plugin in different regions (us)

[EXT-2122]: https://storyblok.atlassian.net/browse/EXT-2122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by BibiSebi** [comment]
will this be a patch version update or a minor?

**Comment by demetriusfeijoo** [comment]
> will this be a patch version update or a minor?

Hey @BibiSebi, in my opinion, we may go with a `minor` here since this PR not only replaced the hardcoded we have with the `region-helper` but also enabled new regions.

What do you think? 🤔

**Review by eunjae-lee — APPROVED** [review]
looks great to me ! 🎉

btw, this is a `patch` release.

`minor` release is only when you "add" a functionality.

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backward compatible functionality is introduced to the public API

https://semver.org/

**Comment by BibiSebi** [comment]
ok I will go with the minor then as it adds new functionality in sense of having the possibility to reach multiple new regions

**Pull request merged**
